---
- name: Backup Config Files Before Hardening
  hosts: all
  become: yes
  vars:
    backup_dir: /var/backup

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    #- name: Backup SSH configuration
    #  copy:
    #   src: /etc/ssh/sshd_config
    #   dest: "{{ backup_dir }}/sshd_config.backup"
    #   backup: yes
        
    - name: Fetch SSHD configuration file
      fetch:
        src: /etc/ssh/sshd_config
        dest: "{{ backup_dir }}/sshd_config.backup"
        flat: yes

    - name: Backup PAM configuration
      copy:
        src: /etc/pam.d/system-auth
        dest: "{{ backup_dir }}/system-auth.backup"
        backup: yes

    #- name: Backup Sysctl configuration
     # copy:
     #   src: /etc/sysctl.conf
     #   dest: "{{ backup_dir }}/sysctl.conf.backup"
     #   backup: yes

   # - name: Backup SELinux configuration
   #   copy:
   #     src: /etc/selinux/config
   #     dest: "{{ backup_dir }}/selinux_config.backup"
   #     backup: yes
    - name: Fetch Sysctl configuration
      fetch:
        src: /etc/sysctl.conf
        dest: "{{ backup_dir }}/sysctl.conf.backup"
        flat: yes

    - name: Fetch SELinux configuration
      fetch:
        src: /etc/selinux/config
        dest: "{{ backup_dir }}/selinux_config.backup"
        flat: yes
        
      - name: Fetch Firewall configuration
      fetch:
        src: /etc/firewalld/firewalld.conf
        dest: "{{ backup_dir }}/firewalld.conf.backup"
        backup: yes

    - name: Fetch Auditd configuration
      fetch:
        src: /etc/audit/auditd.conf
        dest: "{{ backup_dir }}/auditd.conf.backup"
        flat: yes

    - name: Fetch Grub configuration
      fetch:
        src: /etc/default/grub
        dest: "{{ backup_dir }}/grub.backup"
        flat: yes
        
    #- name: Backup Firewall configuration
    #  copy:
    #    src: /etc/firewalld/firewalld.conf
    #    dest: "{{ backup_dir }}/firewalld.conf.backup"
    #    backup: yes

    #- name: Backup Auditd configuration
    #  copy:
    #    src: /etc/audit/auditd.conf
    #    dest: "{{ backup_dir }}/auditd.conf.backup"
    #    backup: yes

   # - name: Backup Grub configuration
   #   copy:
   #     src: /etc/default/grub
   #    dest: "{{ backup_dir }}/grub.backup"
   #   backup: yes
