- name: Update RHEL system
  hosts: all
  become: yes

  tasks:
    - name: Ensure all packages are up-to-date
      yum:
        name: "*"
        state: latest

    - name: Reboot the system if necessary
      command: /sbin/reboot
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['pkg_mgr'] == 'yum'
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for the system to become available after reboot
      wait_for_connection:
        timeout: 300
